# vim: set ft=ansible:
---
- hosts: localhost
  connection: local
  sudo: no
  gather_facts: no
  vars_files:
  - ../vars.yml
  vars:
    cluster_hosts: "{{ groups['tag_env_' ~ cluster_id] }}"
  tasks:
  - fail:
      msg: required values not set
    when: rhsm_user is not defined or rhsm_pass is not defined or cluster_id is not defined and not (skip_subscription_managment | bool)

  - add_host:
      name: "{{ item }}"
      ansible_ssh_user: openshift
      ansible_sudo: yes
      groups: oo_hosts_to_register
    with_items: cluster_hosts

- name: Post register host(s)
  hosts: oo_hosts_to_register
  serial: 1
  tasks:
  - name: Enable rhui extras channel
    command: yum-config-manager --enable rhui-REGION-rhel-server-extras
    when: not (skip_subscription_management | bool)

  - name: Disable all known rhsm repos
    command: subscription-manager repos --disable='*'
    when: not (skip_subscription_management | bool)

  - name: Subscribe only to the ose repo
    command: subscription-manager repos --enable=rhel-7-server-ose-3.1-rpms
    when: not (skip_subscription_management | bool)

- name: Software update
  hosts: oo_hosts_to_register
  tasks:
  - name: Update current package set
    yum:
      name: '*'
      state: latest
    when: not (skip_subscription_management | bool)

