# vim: set ft=ansible:
---
- hosts: localhost
  connection: local
  sudo: no
  gather_facts: no
  vars_files:
  - ../vars.yml
  - ../vars.{{ c_id }}.yml
  vars:
    cluster_hosts: "{{ groups['tag_env_' ~ cluster_id] }}"
  tasks:
  - add_host:
      name: "{{ item }}"
      ansible_ssh_user: openshift
      ansible_sudo: yes
      groups: oo_hosts_to_register
    with_items: cluster_hosts

- name: Register host(s)
  hosts: oo_hosts_to_register
  vars_prompt:
  - name: rhn_username
    prompt: "RHN Username"
    private: no
  - name: rhn_password
    prompt: "RHN Password"
    private: yes
  tasks:
  - name: Enable subscription-manager
    ini_file:
      dest: /etc/yum/pluginconf.d/subscription-manager.conf
      section: main
      option: enabled
      value: 1

  - name: Register host
    redhat_subscription:
      username: "{{ rhn_username }}"
      password: "{{ rhn_password }}"
      state: present
      pool: "^60 Day Supported OpenShift Enterprise|^Employee"

  - name: Enable rhui extras channel
    command: yum-config-manager --enable rhui-REGION-rhel-server-extras

  - name: Disable all known rhsm repos
    command: subscription-manager repos --disable='*'

  - name: Subscribe only to the ose repo
    command: subscription-manager repos --enable=rhel-7-server-ose-3.0-rpms

  - name: Update current package set
    yum:
      name: '*'
      state: latest

